#ifndef _DEFAULTS_H_
#define _DEFAULTS_H_

// Cursor geometry isn't run time configurable.  Should it be?
#define CURSOR_WIDTH 3
#define CURSOR_BOTTOM_ROOM 1
#define CURSOR_TOP_ROOM 1
#define CURSOR_BLINK_SPEED 750

#define DEFAULT_MESSAGE_DURATION 3
#define DEFAULT_COMMAND_COUNT 16

#define DEFAULT_NUMLOCK "false"
#define DEFAULT_HIDE_MOUSE "false"
#define DEFAULT_IGNORE_CAPSLOCK "false"
#define DEFAULT_AUTO_LOGIN "false"
#define DEFAULT_FOCUS_PASSWORD "false"
#define DEFAULT_CURSOR_BLINK "true"
#define DEFAULT_INPUT_HIGHLIGHT "false"

#define DEFAULT_WELCOME_MESSAGE "Welcome to ~h"
#define DEFAULT_USER_PROMPT "Username:"
#define DEFAULT_PASS_PROMPT "Password:"
#define DEFAULT_PASS_MASK " "

#define DEFAULT_CURSOR_COLOR "gray30"
#define DEFAULT_BKGND_STYLE "color"
#define DEFAULT_BKGND_COLOR "black"
#define DEFAULT_PANEL_COLOR "gray30"
#define DEFAULT_MESSAGE_COLOR "white"
#define DEFAULT_MESSAGE_SHADOW_COLOR "gray"
#define DEFAULT_WELCOME_COLOR "white"
#define DEFAULT_WELCOME_SHADOW_COLOR "gray"
#define DEFAULT_PROMPT_COLOR "white"
#define DEFAULT_PROMPT_SHADOW_COLOR "gray"
#define DEFAULT_INPUT_COLOR "deepskyblue4"
#define DEFAULT_INPUT_ALTERNATE_COLOR "royalblue4"
#define DEFAULT_INPUT_SHADOW_COLOR "black"
#define DEFAULT_INPUT_HIGHLIGHT_COLOR "gray75"

#define DEFAULT_MESSAGE_FONT "Verdana:size=20:dpi=75"
#define DEFAULT_WELCOME_FONT "Verdana:size=20:dpi=75"
#define DEFAULT_INPUT_FONT "Verdana:size=20:dpi=75"
#define DEFAULT_PROMPT_FONT "Verdana:size=24:dpi=75"

#define DEFAULT_PANEL_POSN "50% 50% center"
#define DEFAULT_PANEL_WIDTH 600
#define DEFAULT_PANEL_HEIGHT 300
#define DEFAULT_MESSAGE_POSN "50% 30% center"
#define DEFAULT_WELCOME_POSN "50% 40% center"
#define DEFAULT_PASS_PROMPT_POSN "160 180 left"
#define DEFAULT_PASS_INPUT_POSN "180 180 right"
#define DEFAULT_USER_PROMPT_POSN "160 180 left"
#define DEFAULT_USER_INPUT_POSN "180 180 right"
#define DEFAULT_MESSAGE_SHADOW_OFFSET "0 0"
#define DEFAULT_WELCOME_SHADOW_OFFSET "0 0"
#define DEFAULT_PROMPT_SHADOW_OFFSET "0 0"
#define DEFAULT_PASS_INPUT_SIZE "250 24"
#define DEFAULT_USER_INPUT_SIZE "250 24"
#define DEFAULT_INPUT_SHADOW_OFFSET "0 0"

#endif /* _DEFAULTS_H_ */
