sedprg="s/\(static unsigned int\)/INLINE_DECL \1/"
sedprg="$sedprg;s/^const struct keyword \*/unsigned int/"
sedprg="$sedprg;s/return &wordlist\[key\];/return wordlist[key].code;/"
cat <<EOF | gperf -t | sed "$sedprg" >keywords.c
%{
#include <string.h>
#include "keywords.h"
#if __STDC_VERSION__ >= 199901L
#define INLINE_DECL inline
#elif defined(__GNUC__)
#define INLINE_DECL __inline
#else
#define INLINE_DECL
#endif
%}
%readonly-tables
%language=ANSI-C
%define hash-function-name keyword_hash
%define lookup-function-name lookup_keyword
%compare-strncmp
struct keyword { char *name; int code; };
%%
mod1, KEYWORD_MOD1
m1, KEYWORD_MOD1
mod2, KEYWORD_MOD2
m2, KEYWORD_MOD2
mod3, KEYWORD_MOD3
m3, KEYWORD_MOD3
mod4, KEYWORD_MOD4
m4, KEYWORD_MOD4
mod5, KEYWORD_MOD5
m5, KEYWORD_MOD5
ctrl, KEYWORD_CTRL
c, KEYWORD_C
left, KEYWORD_LEFT
l, KEYWORD_LEFT
right, KEYWORD_RIGHT
r, KEYWORD_RIGHT
above, KEYWORD_ABOVE
a, KEYWORD_ABOVE,
below, KEYWORD_BELOW
b, KEYWORD_BELOW
tile, KEYWORD_TILE
stretch, KEYWORD_STRETCH
color, KEYWORD_COLOR
yes, KEYWORD_TRUE
on, KEYWORD_TRUE
true, KEYWORD_TRUE
no, KEYWORD_FALSE
off, KEYWORD_FALSE
false, KEYWORD_FALSE
shift, KEYWORD_SHIFT
s, KEYWORD_SHIFT
exec, KEYWORD_EXEC
switch-session, KEYWORD_SWITCH_SESSION
EOF

cat >keywords.h <<EOF
// Automatically generated by keywords.sh
// Don't edit sil vous plait

int lookup_keywords(register const char *str, register unsigned int len);
EOF
keynum=1
for key in \
    TRUE FALSE \
    LEFT RIGHT ABOVE BELOW CENTER \
    TILE STRETCH COLOR \
    MOD1 MOD2 MOD3 MOD4 MOD5 CTRL SHIFT \
    C \
    EXEC SWITCH_SESSION
do
    echo "#define KEYWORD_$key $keynum" >>keywords.h
    keynum=$((keynum+1))
done
